language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hoopikhoop/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hoopikhoop/react-test npm test 

after_success:
  - docker build -t hoopikhoop/multi-client ./client
  - docker build -t hoopikhoop/multi-nginx ./nginx
  - docker build -t hoopikhoop/multi-server ./server
  - docker build -t hoopikhoop/multi-worker ./worker

  # Travis CI will push images to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hoopikhoop/multi-client
  - docker push hoopikhoop/multi-nginx
  - docker push hoopikhoop/multi-server
  - docker push hoopikhoop/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-2-48509454910
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY